// Code generated by "stringer -type=Error"; DO NOT EDIT.

package cwa

import "strconv"

const _Error_name = "NotFoundErrorPermissionDeniedErrorInvalidArgumentErrorUnknownErrorErrNone"

var _Error_index = [...]uint8{0, 13, 34, 54, 66, 73}

func (i Error) String() string {
	i -= -4
	if i < 0 || i >= Error(len(_Error_index)-1) {
		return "Error(" + strconv.FormatInt(int64(i+-4), 10) + ")"
	}
	return _Error_name[_Error_index[i]:_Error_index[i+1]]
}
