// Code generated by protoc-gen-go. DO NOT EDIT.
// source: archway.proto

package archway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_archway_0923e72e68ae88f5, []int{0}
}
func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (dst *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(dst, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

type Handler struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAtUnixUtc     int64    `protobuf:"varint,2,opt,name=created_at_unix_utc,json=createdAtUnixUtc,proto3" json:"created_at_unix_utc,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Module               []byte   `protobuf:"bytes,4,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler) Reset()         { *m = Handler{} }
func (m *Handler) String() string { return proto.CompactTextString(m) }
func (*Handler) ProtoMessage()    {}
func (*Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_archway_0923e72e68ae88f5, []int{1}
}
func (m *Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler.Unmarshal(m, b)
}
func (m *Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler.Marshal(b, m, deterministic)
}
func (dst *Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler.Merge(dst, src)
}
func (m *Handler) XXX_Size() int {
	return xxx_messageInfo_Handler.Size(m)
}
func (m *Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Handler proto.InternalMessageInfo

func (m *Handler) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Handler) GetCreatedAtUnixUtc() int64 {
	if m != nil {
		return m.CreatedAtUnixUtc
	}
	return 0
}

func (m *Handler) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Handler) GetModule() []byte {
	if m != nil {
		return m.Module
	}
	return nil
}

type Handlers struct {
	Handlers             []*Handler `protobuf:"bytes,1,rep,name=handlers,proto3" json:"handlers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Handlers) Reset()         { *m = Handlers{} }
func (m *Handlers) String() string { return proto.CompactTextString(m) }
func (*Handlers) ProtoMessage()    {}
func (*Handlers) Descriptor() ([]byte, []int) {
	return fileDescriptor_archway_0923e72e68ae88f5, []int{2}
}
func (m *Handlers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handlers.Unmarshal(m, b)
}
func (m *Handlers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handlers.Marshal(b, m, deterministic)
}
func (dst *Handlers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handlers.Merge(dst, src)
}
func (m *Handlers) XXX_Size() int {
	return xxx_messageInfo_Handlers.Size(m)
}
func (m *Handlers) XXX_DiscardUnknown() {
	xxx_messageInfo_Handlers.DiscardUnknown(m)
}

var xxx_messageInfo_Handlers proto.InternalMessageInfo

func (m *Handlers) GetHandlers() []*Handler {
	if m != nil {
		return m.Handlers
	}
	return nil
}

type Id struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic                string   `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_archway_0923e72e68ae88f5, []int{3}
}
func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (dst *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(dst, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Id) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type Event struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAtUnixUtc     int64    `protobuf:"varint,2,opt,name=created_at_unix_utc,json=createdAtUnixUtc,proto3" json:"created_at_unix_utc,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_archway_0923e72e68ae88f5, []int{4}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (dst *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(dst, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetCreatedAtUnixUtc() int64 {
	if m != nil {
		return m.CreatedAtUnixUtc
	}
	return 0
}

func (m *Event) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Event) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Nil)(nil), "within.olin.archway.Nil")
	proto.RegisterType((*Handler)(nil), "within.olin.archway.Handler")
	proto.RegisterType((*Handlers)(nil), "within.olin.archway.Handlers")
	proto.RegisterType((*Id)(nil), "within.olin.archway.Id")
	proto.RegisterType((*Event)(nil), "within.olin.archway.Event")
}

func init() { proto.RegisterFile("archway.proto", fileDescriptor_archway_0923e72e68ae88f5) }

var fileDescriptor_archway_0923e72e68ae88f5 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0xa4, 0x7f, 0xa7, 0xad, 0xc8, 0x56, 0x34, 0x04, 0x85, 0xb0, 0xa7, 0x20, 0x98,
	0x43, 0xbd, 0x78, 0xad, 0xb6, 0xb4, 0x01, 0xed, 0x21, 0xd0, 0x8b, 0x97, 0xb2, 0x66, 0x17, 0xba,
	0x10, 0x37, 0x21, 0x9d, 0xfe, 0xf1, 0xcb, 0xf9, 0xd9, 0x84, 0x64, 0xad, 0x82, 0x69, 0x3c, 0x88,
	0xb7, 0xdd, 0xbc, 0xd9, 0xdf, 0xbc, 0x37, 0x43, 0xa0, 0xcf, 0xb2, 0x68, 0xb5, 0x63, 0x6f, 0x7e,
	0x9a, 0x25, 0x98, 0x90, 0xc1, 0x4e, 0xe2, 0x4a, 0x2a, 0x3f, 0x89, 0xa5, 0xf2, 0xb5, 0x44, 0x1b,
	0x60, 0xcd, 0x65, 0x4c, 0xb7, 0xd0, 0x9a, 0x31, 0xc5, 0x63, 0x91, 0x91, 0x13, 0x30, 0x25, 0xb7,
	0x0d, 0xd7, 0xf0, 0x3a, 0xa1, 0x29, 0x39, 0xb9, 0x81, 0x41, 0x94, 0x09, 0x86, 0x82, 0x2f, 0x19,
	0x2e, 0x37, 0x4a, 0xee, 0x97, 0x1b, 0x8c, 0x6c, 0xd3, 0x35, 0x3c, 0x2b, 0x3c, 0xd5, 0xd2, 0x08,
	0x17, 0x4a, 0xee, 0x17, 0x18, 0x91, 0x33, 0x68, 0x60, 0x92, 0xca, 0xc8, 0xb6, 0x72, 0x42, 0x71,
	0x21, 0xe7, 0xd0, 0x7c, 0x4d, 0xf8, 0x26, 0x16, 0x76, 0xdd, 0x35, 0xbc, 0x5e, 0xa8, 0x6f, 0x74,
	0x0c, 0x6d, 0xdd, 0x77, 0x4d, 0xee, 0xa0, 0xbd, 0xd2, 0x67, 0xdb, 0x70, 0x2d, 0xaf, 0x3b, 0xbc,
	0xf4, 0x4b, 0x2c, 0xfb, 0xfa, 0x41, 0x78, 0xa8, 0xa6, 0xd7, 0x60, 0x06, 0xfc, 0x87, 0xf1, 0x83,
	0x13, 0xf3, 0x9b, 0x13, 0x9a, 0x42, 0x63, 0xb2, 0x15, 0x0a, 0xff, 0x27, 0x27, 0x81, 0x3a, 0x67,
	0xc8, 0x74, 0xca, 0xfc, 0x3c, 0x7c, 0xb7, 0xa0, 0x15, 0x28, 0x14, 0x59, 0x92, 0x92, 0x27, 0xe8,
	0x3f, 0xe4, 0xa4, 0xcf, 0x69, 0x57, 0x46, 0x74, 0x2a, 0x55, 0x5a, 0x23, 0x33, 0xe8, 0x8f, 0x45,
	0x2c, 0xbe, 0x70, 0x17, 0xa5, 0x0f, 0x02, 0xfe, 0x2b, 0x69, 0x02, 0x30, 0x15, 0xf8, 0x67, 0x4c,
	0x00, 0xbd, 0x47, 0xb9, 0xc6, 0xc3, 0x4e, 0xed, 0xd2, 0xfa, 0xb9, 0x8c, 0x9d, 0xab, 0x2a, 0xd2,
	0x3a, 0x77, 0xd4, 0x2d, 0x46, 0x55, 0xac, 0xcb, 0x29, 0xad, 0xcf, 0x35, 0xe7, 0x68, 0x17, 0x5a,
	0x23, 0x23, 0x68, 0x4f, 0x05, 0x16, 0x8c, 0xa3, 0xb1, 0x2a, 0xe0, 0xb4, 0x76, 0xdf, 0x79, 0x6e,
	0xe9, 0x4f, 0x2f, 0xcd, 0xfc, 0x57, 0xba, 0xfd, 0x08, 0x00, 0x00, 0xff, 0xff, 0x75, 0x75, 0x1d,
	0x30, 0x5b, 0x03, 0x00, 0x00,
}
