// Code generated by "stringer -type=Errno"; DO NOT EDIT.

package dagger

import "strconv"

const _Errno_name = "ErrorNoneErrorBadURLErrorBadURLInputErrorUnknownScheme"

var _Errno_index = [...]uint8{0, 9, 20, 36, 54}

func (i Errno) String() string {
	if i < 0 || i >= Errno(len(_Errno_index)-1) {
		return "Errno(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Errno_name[_Errno_index[i]:_Errno_index[i+1]]
}
