FROM xena/go:1.10 AS build
RUN apk add --no-cache build-base
COPY . /root/go/src/github.com/Xe/olin
WORKDIR /root/go/src/github.com/Xe/olin
RUN GOBIN=/ go install ./cmd/cwa-cgi

FROM xena/alpine
COPY ./run/run.sh /run.sh
COPY --from=build /root/go/src/github.com/Xe/olin/cmd/cwa-cgi/testdata/test.wasm /main.wasm
COPY --from=build /cwa-cgi /cwa-cgi
WORKDIR /
CMD ["/run.sh"]